# Generated by Django 3.1.2 on 2020-11-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('message', models.TextField()),
                ('recommendations', models.PositiveIntegerField(default=0)),
                ('un_recommendations', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
