# Generated by Django 3.1.2 on 2020-11-07 19:23

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields
import inventory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('slug', models.SlugField(blank=True)),
                ('logo', models.ImageField(upload_to=inventory.models.brand_uploader)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=6)),
                ('opacity', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField(blank=True)),
                ('breadth', models.FloatField(blank=True)),
                ('width', models.FloatField(blank=True)),
                ('thickness', models.FloatField(blank=True)),
                ('diameter', models.FloatField(blank=True)),
                ('size_in_standard_unit', models.FloatField(blank=True)),
                ('size_in_other_unit', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True)),
                ('main_image', models.ImageField(upload_to=inventory.models.product_main_uploader)),
                ('is_active', models.BooleanField(default=False)),
                ('on_sale', models.BooleanField(default=False)),
                ('base_price', models.FloatField()),
                ('profit_percentage', models.FloatField()),
                ('sale_percentage', models.FloatField(blank=True)),
                ('sold', models.PositiveIntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
                ('colors', models.ManyToManyField(to='inventory.Color')),
                ('dimensions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.dimension')),
                ('reviews', models.ManyToManyField(to='feedback.Review')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=inventory.models.product_batch_uploader)),
                ('product', models.ForeignKey(on_delete=django.db.models.fields.CharField, to='inventory.product')),
            ],
        ),
    ]
