# Generated by Django 3.1.2 on 2020-11-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20201108_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
