# Generated by Django 3.1.2 on 2020-11-08 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20201108_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='profit_percentage',
            new_name='sale_price',
        ),
    ]
