# Generated by Django 3.1.2 on 2020-11-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20201108_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimension',
            name='type',
            field=models.CharField(choices=[(0, '3d Cube')], default=0, max_length=55),
            preserve_default=False,
        ),
    ]
